server.port=${SERVICE_PORT:8003}

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:shipping}
spring.datasource.username=${POSTGRES_USER:shipping}
spring.datasource.password=${POSTGRES_PASSWORD:shippingpass}
spring.datasource.driver-class-name=org.postgresql.Driver
